package routers

import (
	"gin-init/controller/api/v1/authController"
	"gin-init/controller/api/v1/tagController"
	_ "gin-init/docs" // docs is generated by Swag CLI, you have to import it.
	jwt "gin-init/middleware"
	"gin-init/pkg/e"
	"gin-init/pkg/setting"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

func InitRouter() *gin.Engine {
	r := gin.New()

	gin.SetMode(setting.RunMode)
	r.Use(gin.Logger(), gin.Recovery(), cors.Default())
	r.NoRoute(e.NotFound())

	r.GET("/test", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "test",
		})
	})

	// use ginSwagger middleware to
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.GET("/auth", authController.GetAuth)

	// 注册路由
	apiv1 := r.Group("/api/v1")
	apiv1.Use(jwt.JWT())
	{
		// Tag
		apiv1.GET("/tags", tagController.Get)
		apiv1.POST("/tag", tagController.Create)
		apiv1.DELETE("/tags/:id", tagController.Destroy)
		apiv1.PUT("/tags/:id", tagController.Update)

	}

	return r
}
